spring.application.name=HauppaugeChromecast
spring.main.allow-bean-definition-overriding=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/
allente_channels_api_url=https://cs-vcb.allente.se/epg/events

app.programme_info_fade_animation_duration=.3s
app.channel_item_display_animation_duration=1s
app.last_scrolled_threshold=400
app.last_scrolled_handler_timeout=500
