# Enable or disable live reload (for browser auto-reload)
# spring.devtools.livereload.enabled=true
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
