spring.application.name=HauppaugeChromecast
spring.main.allow-bean-definition-overriding=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/
allente_channels_api_url=https://cs-vcb.allente.se/epg/events
