spring.application.name=HauppaugeChromecast
spring.main.allow-bean-definition-overriding=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.web.resources.static-locations=classpath:/static/
allente_channels_api_url=https://cs-vcb.allente.se/epg/events

app.default_locale=en
app.animations.programme_info_fade_animation_duration=.3
app.animations.channel_item_display_animation_duration=1
app.animations.developer_console_message_insert_animation_duration=.4
app.last_scrolled_threshold=400
app.last_scrolled_handler_timeout=500
app.developer_console.last_inserted_message_cluster_threshold=1000
app.developer_console.initial-height=500
app.developer_console.animation_duration=.5
app.developer_console.message_limit=20
app.main_left_panel_default_width=350
